apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: krateo-template-aws-stack
spec:
  package: ghcr.io/krateoplatformops/krateo-template-awsstack:latest
  packagePullPolicy: Always
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 1
